### ISSUE TITLE
WIP status makes PR stuck forever

### ISSUE THREAD

**Issue by fmigneault** [wip/action#44]
I have a project that employs this action. 
For some reason I cannot figure out, WIP is always blocking my PRs without any apparent reason (to me at least).

For example this PR: 
https://github.com/crim-ca/weaver/pull/244

As shown in the below image, all my tests are passing, I got all mandatory branch protection approvals, etc. 
The only thing that blocks my PR is the "incomplete" WIP action check, which has requirement of `WIP (action)` defined in branch protection as per the README of this repo.
 
It is configured here: https://github.com/crim-ca/weaver/blob/wip-action/.github/workflows/pr-labeler.yml 

Any idea of what might be at cause of this issue?
Thanks!

![image](https://user-images.githubusercontent.com/19194484/115912815-cfba8580-a43d-11eb-9ccf-9b0ffce7aa0d.png)

**Comment by gr2m** [comment]
I do not think that it's a problem with WIP.

I see the following message for that workflow file on GitHub

>  This scheduled workflow is disabled because there hasn't been activity in this repository for at least 60 days. 

https://github.com/crim-ca/weaver/actions/workflows/pr-labeler.yml

I don't know why the action isn't triggered by the pull request event.

Can you try to create a separate workflow file, just for WIP?

**Comment by gr2m** [comment]
It fails because the action cannot handle the schedule event. You have to use the `if` expression to make sure the WIP action only runs when triggered by a `pull_request` event

**Comment by fmigneault** [comment]
@gr2m Thanks for your help. The `if` resolved the problem.
